### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by lokka30** [SnkSynthesis/voxel-game#3]
Some screenshots in the README could be a nice touch. :)

If I manage to get it to compile (#2), I can take some and PR it.

**Comment by SnkSynthesis** [comment]
Hi @lokka30 

Thanks for the suggestion! I've added a screenshot to the README. :)

For #2 I have updated `pom.xml` to support more platforms including macOS ARM64. Haven't tested to see if it works on macOS.

**Comment by lokka30** [comment]
Great! Oh and, I'm sorry I forgot to post that I actually took some screenshots after I posted this issue! Feel free to add them if you want. :)

<details>
<summary>View screenshots</summary>

![1](https://user-images.githubusercontent.com/59464084/159194486-96eb643a-7133-42b5-bfae-ab5dd1de692e.jpg)
![2](https://user-images.githubusercontent.com/59464084/159194492-900062f5-6c43-4614-a046-33416944a1ec.jpg)
![3](https://user-images.githubusercontent.com/59464084/159194493-ae918916-e8a8-458b-9002-3a732502e258.jpg)
![4](https://user-images.githubusercontent.com/59464084/159194496-903a329c-421e-4f6f-9623-d79039402ffe.jpg)
![5](https://user-images.githubusercontent.com/59464084/159194497-39af25b9-d347-4d87-8a6d-c8866347768a.jpg)
![6](https://user-images.githubusercontent.com/59464084/159194498-06a72d85-beb7-4058-8b5d-96c0d76788d7.jpg)
![7](https://user-images.githubusercontent.com/59464084/159194499-c19f024c-4008-4b20-bfb7-8542d0adcc0d.jpg)

</details>

**Comment by SnkSynthesis** [comment]
Okay. I've added some of the screenshots that you have sent. Thanks @lokka30!
